Repository shinheekim/four-chelin, pull requests merged in 2024-11, with the labels that each got.

#7 Feat: 키워드를 통한 가게 조회 기능/Member 기능구현 마무리 예정
  build.gradle
  src/main/java/com/example/fourchelin/FourChelinApplication.java
  src/main/java/com/example/fourchelin/common/baseentity/Timestamped.java
  src/main/java/com/example/fourchelin/common/config/JPAConfiguration.java
  src/main/java/com/example/fourchelin/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/fourchelin/common/template/RspTemplate.java
  src/main/java/com/example/fourchelin/domain/store/controller/StoreController.java
  src/main/java/com/example/fourchelin/domain/store/dto/request/StoreRequest.java
  src/main/java/com/example/fourchelin/domain/store/dto/response/StorePageResponse.java
  src/main/java/com/example/fourchelin/domain/store/dto/response/StoreResponse.java
  src/main/java/com/example/fourchelin/domain/store/entity/Store.java
  src/main/java/com/example/fourchelin/domain/store/enums/StoreCategory.java
  src/main/java/com/example/fourchelin/domain/store/enums/StoreStatus.java
  src/main/java/com/example/fourchelin/domain/store/exception/StoreException.java
  src/main/java/com/example/fourchelin/domain/store/repository/StoreRepository.java
  src/main/java/com/example/fourchelin/domain/store/repository/support/StoreRepositoryCustom.java
  src/main/java/com/example/fourchelin/domain/store/repository/support/StoreRepositoryCustomImpl.java
  src/main/java/com/example/fourchelin/domain/store/service/StoreService.java
Labels: 🧑‍💻feature

#13 feat: 웨이팅 entity, repositoy 설계 / 웨이팅 신청하기 구현 예정
  src/main/java/com/example/fourchelin/domain/waiting/entity/Waiting.java
  src/main/java/com/example/fourchelin/domain/waiting/enums/WaitingMealType.java
  src/main/java/com/example/fourchelin/domain/waiting/enums/WaitingStatus.java
  src/main/java/com/example/fourchelin/domain/waiting/enums/WaitingType.java
  src/main/java/com/example/fourchelin/domain/waiting/repository/WaitingRepository.java
Labels: enhancement

#14 Feat: 키워드 검색 기능 구현 / 검색목록 저장 및 조회 구현 예정
  build.gradle
  src/main/java/com/example/fourchelin/common/template/RspTemplate.java
  src/main/java/com/example/fourchelin/domain/search/controller/SearchController.java
  src/main/java/com/example/fourchelin/domain/search/dto/response/SearchResponse.java
  src/main/java/com/example/fourchelin/domain/search/entity/PopularSearch.java
  src/main/java/com/example/fourchelin/domain/search/entity/SearchHistory.java
  src/main/java/com/example/fourchelin/domain/search/exception/SearchException.java
  src/main/java/com/example/fourchelin/domain/search/service/SearchService.java
  src/main/java/com/example/fourchelin/domain/store/entity/Store.java
  src/main/java/com/example/fourchelin/domain/store/repository/support/StoreRepositoryCustom.java
  src/main/java/com/example/fourchelin/domain/store/repository/support/StoreRepositoryCustomImpl.java
  src/test/java/com/example/fourchelin/search/service/SearchServiceTest.java
Labels: 🧑‍💻feature

#17 Issue/5
  build.gradle
  src/main/java/com/example/fourchelin/FourChelinApplication.java
  src/main/java/com/example/fourchelin/common/config/WebSecurityConfig.java
  src/main/java/com/example/fourchelin/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/fourchelin/common/filter/MemberAuthenticationFilter.java
  src/main/java/com/example/fourchelin/common/security/UserDetailsImpl.java
  src/main/java/com/example/fourchelin/common/security/UserDetailsServiceImpl.java
  src/main/java/com/example/fourchelin/domain/member/controller/MemberController.java
  src/main/java/com/example/fourchelin/domain/member/dto/request/LoginRequest.java
  src/main/java/com/example/fourchelin/domain/member/dto/request/SignupRequest.java
  src/main/java/com/example/fourchelin/domain/member/dto/response/LoginResponse.java
  src/main/java/com/example/fourchelin/domain/member/dto/response/SignupResponse.java
  src/main/java/com/example/fourchelin/domain/member/entity/Member.java
  src/main/java/com/example/fourchelin/domain/member/enums/MemberRole.java
  src/main/java/com/example/fourchelin/domain/member/exception/MemberException.java
  src/main/java/com/example/fourchelin/domain/member/repository/MemberRepository.java
  src/main/java/com/example/fourchelin/domain/member/repository/support/MemberRepositoryCustom.java
  src/main/java/com/example/fourchelin/domain/member/repository/support/MemberRepositoryCustomImpl.java
  src/main/java/com/example/fourchelin/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 🧑‍💻feature

#18 Feat: 웨이팅 예약하기 API 구현 / 웨이팅 조회 API 구현 예정
  build.gradle
  src/main/java/com/example/fourchelin/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/fourchelin/domain/waiting/controller/WaitingController.java
  src/main/java/com/example/fourchelin/domain/waiting/dto/request/WaitingRequest.java
  src/main/java/com/example/fourchelin/domain/waiting/dto/response/WaitingResponse.java
  src/main/java/com/example/fourchelin/domain/waiting/entity/Waiting.java
  src/main/java/com/example/fourchelin/domain/waiting/repository/WaitingRepository.java
  src/main/java/com/example/fourchelin/domain/waiting/service/WaitingService.java
  src/main/resources/application.yml
  src/test/java/com/example/fourchelin/domain/waiting/service/WaitingServiceTest.java
Labels: 🧑‍💻feature

#23 [#22] fix: /api/searches에 익명 사용자 접근 허용 가능하도록 Filter 수정
  src/main/java/com/example/fourchelin/common/filter/MemberAuthenticationFilter.java
  src/main/java/com/example/fourchelin/domain/member/controller/MemberController.java
Labels: bug

#24 Feat: 검색목록 저장 및 조회기능 구현 / 인기검색어 저장 및 조회 기능 구현 예정
  src/main/java/com/example/fourchelin/common/config/WebSecurityConfig.java
  src/main/java/com/example/fourchelin/common/filter/MemberAuthenticationFilter.java
  src/main/java/com/example/fourchelin/domain/search/controller/SearchController.java
  src/main/java/com/example/fourchelin/domain/search/entity/SearchHistory.java
  src/main/java/com/example/fourchelin/domain/search/repository/SearchHistoryRepository.java
  src/main/java/com/example/fourchelin/domain/search/repository/support/SearchHistoryRepositoryCustom.java
  src/main/java/com/example/fourchelin/domain/search/repository/support/SearchHistoryRepositoryCustomImpl.java
  src/main/java/com/example/fourchelin/domain/search/service/SearchService.java
  src/main/java/com/example/fourchelin/domain/store/entity/Store.java
  src/test/java/com/example/fourchelin/search/service/SearchServiceTest.java
Labels: 🧑‍💻feature

#30 Fix: 웨이팅 대기열 관리 완료 / 웨이팅 대기열 미루기, 조회, 삭제 예정
  src/main/java/com/example/fourchelin/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/fourchelin/domain/waiting/dto/response/WaitingResponse.java
  src/main/java/com/example/fourchelin/domain/waiting/exception/WaitingAlreadyExistException.java
  src/main/java/com/example/fourchelin/domain/waiting/repository/WaitingRepository.java
  src/main/java/com/example/fourchelin/domain/waiting/service/WaitingService.java
  src/test/java/com/example/fourchelin/domain/waiting/service/WaitingServiceTest.java
Labels: 🧑‍💻feature

#32 Feat&Fix: 웨이팅 정보 조회 및 웨이팅 등록 시 문제 해결 / 웨이팅 삭제 구현 예정
  .github/pull_request_template.md
  src/main/java/com/example/fourchelin/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/fourchelin/domain/waiting/controller/WaitingController.java
  src/main/java/com/example/fourchelin/domain/waiting/dto/response/WaitingInfoResponse.java
  src/main/java/com/example/fourchelin/domain/waiting/enums/WaitingStatus.java
  src/main/java/com/example/fourchelin/domain/waiting/repository/WaitingRepository.java
  src/main/java/com/example/fourchelin/domain/waiting/service/WaitingService.java
  src/test/java/com/example/fourchelin/domain/waiting/service/WaitingServiceTest.java
Labels: bug, 🧑‍💻feature

#35 Feat: 웨이팅 삭제 / 웨이팅 시 동시성 이슈를 검증할 수 있는 테스트 코드 작성 예정
  src/main/java/com/example/fourchelin/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/fourchelin/domain/waiting/controller/WaitingController.java
  src/main/java/com/example/fourchelin/domain/waiting/entity/Waiting.java
  src/main/java/com/example/fourchelin/domain/waiting/exception/WaitingNotAuthorizedException.java
  src/main/java/com/example/fourchelin/domain/waiting/exception/WaitingNotFoundException.java
  src/main/java/com/example/fourchelin/domain/waiting/service/WaitingService.java
  src/test/java/com/example/fourchelin/domain/waiting/service/WaitingServiceTest.java
Labels: 🧑‍💻feature

#43 Feat: In-memory Cache를 적용한 v2 인기검색어 조회 구현 / Redis를 이용한 인기검색어 저장 구현 예정
  src/main/java/com/example/fourchelin/domain/search/controller/SearchController.java
  src/main/java/com/example/fourchelin/domain/search/repository/support/PopularKeywordRepositoryCustom.java
  src/main/java/com/example/fourchelin/domain/search/repository/support/PopularKeywordRepositoryCustomImpl.java
  src/main/java/com/example/fourchelin/domain/search/service/KeywordCacheService.java
  src/main/java/com/example/fourchelin/domain/search/service/SearchService.java
Labels: 🧑‍💻feature
